apiVersion: v1
kind: ConfigMap
metadata:
  name: network-cost-scheduler-config
  namespace: customized-ks
data:
  nc-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection: 
      leaderElect: {{ .Values.scheduler.leaderElect }}
    clientConnection:
      kubeconfig: "/etc/kubernetes/cred/my-scheduler.kubeconfig"
    profiles:
      - schedulerName: network-cost-aware-scheduler
        plugins:
          queueSort:
            enabled:
              - name: TopologicalcnSort
            disabled:
              - name: "*"
          preFilter:
            enabled:
              - name: NetworkOverhead
          filter:
            enabled:
              - name: NetworkOverhead
          score:
            disabled:
              - name: NodeResourcesFit
            enabled:
              - name: NetworkOverhead
                weight: 5
        pluginConfig:
          - name: TopologicalcnSort
            args:
              namespaces:
                - "default"
          - name: NetworkOverhead
            args:
              namespaces:
                - "default"
              weightsName: "NetperfCosts" # or Dijkstra
              networkTopologyName: "net-topology-test"


              
