kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: scheduler-plugins-controller
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app: scheduler-plugins-controller
  template:
    metadata:
      labels:
        app: scheduler-plugins-controller
    spec:
      serviceAccountName: {{ .Values.controller.name }}
      containers:
      - name: scheduler-plugins-controller
        image: {{ .Values.controller.image }}
        imagePullPolicy: IfNotPresent
        {{- with .Values.controller.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
  name: {{ .Values.scheduler.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: scheduler
  replicas: {{ .Values.scheduler.replicaCount }}
  template:
    metadata:
      labels:
        component: scheduler
    spec:
      serviceAccountName: {{ .Values.scheduler.name }}
      containers:
      - command: {{- toYaml .Values.scheduler.command | nindent 8 }}
        args:
        - --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig
        - --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig
        - --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig
        - --bind-address=127.0.0.1
        image: {{ .Values.scheduler.image }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
          initialDelaySeconds: 15
        name: scheduler-plugins-scheduler
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10259
            scheme: HTTPS
        {{- with .Values.scheduler.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          runAsUser: 0  # Run as root
        volumeMounts:
        - name: scheduler-config
          mountPath: /var/lib/rancher/k3s/server/cred/scheduler.kubeconfig
          subPath: scheduler.kubeconfig
          readOnly: true
        - name: scheduler-certs
          mountPath: /var/lib/rancher/k3s/server/tls
          readOnly: true
      hostNetwork: false
      hostPID: false
      volumes:
      - name: scheduler-config
        secret:
          secretName: scheduler-kubeconfig  # Reference the secret created earlier
      - name: scheduler-certs
        hostPath:
          path: /var/lib/rancher/k3s/server/tls
          type: Directory
      nodeSelector:
        kubernetes.io/hostname: masternodecluster1  # Ensure the pod is scheduled on the master node
