kind: Deployment
apiVersion: apps/v1
metadata:
  name: network-cost-aware-controller
  namespace: customized-ks
  labels:
    app: network-cost-aware-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-cost-aware-controller
  template:
    metadata:
      labels:
        app: network-cost-aware-controller
    spec:
      serviceAccountName: network-cost-aware-controller
      containers:
        - name: network-cost-aware-controller
          image: audhub/controller-v0.30.6:latest
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-cost-aware-scheduler
  namespace: customized-ks
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ns-scheduler
      tier: ns-control-plane
  template:
    metadata:
      labels:
        component: ns-scheduler
        tier: ns-control-plane
    spec:
      nodeSelector:
        kubernetes.io/hostname: "masternodecluster1"
      containers:
        - image: audhub/fspaas:kube-scheduler-v0.30.6
          command:
            - /bin/kube-scheduler
            - --authentication-kubeconfig=/etc/kubernetes/cred/my-scheduler.kubeconfig
            - --authorization-kubeconfig=/etc/kubernetes/cred/my-scheduler.kubeconfig
            - --config=/etc/kubernetes/nc-scheduler-config.yaml
            - -v=9
          name: network-cost-aware-scheduler
          securityContext:
            #privileged: true
            runAsUser: 0  # Run as root to ensure it can access the file
            runAsGroup: 0 # Ensure it has the correct group permissions
          volumeMounts:
            - mountPath: /etc/kubernetes/
              name: ns-scheduler-config-volume
            - mountPath: /etc/kubernetes/cred/
              name: ns-scheduler-kubeconfig-volume
            - mountPath: /var/lib/rancher/k3s/server/tls
              name: ns-scheduler-tls-volume
              readOnly: true
              
      hostNetwork: false
      hostPID: false
      volumes:
        - name: ns-scheduler-config-volume
          configMap:
            name: network-cost-scheduler-config
        - name: ns-scheduler-kubeconfig-volume
          hostPath:
            path: /var/lib/rancher/k3s/server/cred  # Path on the host machine
            type: Directory
        - name: ns-scheduler-tls-volume
          hostPath:
            path: /var/lib/rancher/k3s/server/tls  # Path on the host machine
            type: Directory