apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.scheduler.name }}
  namespace: customized-ks
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.name }}
  namespace: customized-ks
